language: python
dist: xenial
python: "3.6"

jobs:
  include:
    - stage: test
      python: "3.6"
      script: nox -s ci-3.6

    - stage: test
      python: "3.7"
      script: nox -s ci-3.7
      after_success: codecov

    - stage: docs
      if: branch = release/docs
      before_install:
        - nvm install 10
        - nvm use 10
        - npm install
      script: npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        repo: bocadilloproject/bocadilloproject.github.io
        github-token: $GITHUB_TOKEN
        target-branch: master
        local-dir: docs/.vuepress/dist

    - stage: release
      if: tag IS present
      deploy:
        provider: pypi
        distributions: "sdist bdist_wheel"
        username: $PYPI_USERNAME
        password: $PYPI_PASSWORD
